### ISSUE TITLE
What is the backbone of your object detector?

### ISSUE THREAD

**Issue by BIGJUN777** [BigRedT/no_frills_hoi_det#10]
Hello, thank you for releasing the codes for your nice work.
Did you use the Faster RCNN with Resnet-152-FPN backbone or just Faster RCNN with Resnet-152?

Thanks.

**Comment by BigRedT** [comment]
Hi @BIGJUN777, I think the faster-rcnn code base we used did not support FPN. They have something called the FPN baseline which just seems like the baseline configuration of image size and the number of proposals used as the baseline in the FPN paper.

I used regular Resnet-152 if I remember correctly. While I provide object detector features for HICO-Det dataset, if you are looking at extracting your own features, at least one other user was able to reproduce my results using the following model provided with the pytorch-faster-rcnn repository: https://drive.google.com/drive/folders/0B7fNdx_jAqhtaVFMeGhVWkpsT1U

**Comment by BIGJUN777** [comment]
Thanks a lot.
