### ISSUE TITLE
Problems with the bboxes from the file selected_coco_cls_dets.hdf5 file

### ISSUE THREAD

**Issue by MathiasHaudgaard** [BigRedT/no_frills_hoi_det#3]
I'm having problems understanding why these bounding boxes in the image below don't fit the two persons. I'm extracting the bboxes from the selected_coco_cls_dets file.

![image](https://user-images.githubusercontent.com/10813266/57572921-85db5f00-7421-11e9-9b8a-cd3f2a8e1533.png)

**Comment by BigRedT** [comment]
The boxes are stored as [x1,y1,x2,y2], where x1,y1 are top left coordinates and x2 and y2 are bottom right coordinates. I see that the docs/selected_coco_cls_dets.md incorrectly says it is x,y,w,h. I will update the doc tonight. Thanks for pointing this out. It would be great if you can confirm in this example that it is indeed the case (actually the coordinates seem to make sense by simply looking at the axis of the figure)!

**Comment by BigRedT** [comment]
Docs updated to correct bounding box format in various hdf5 files!

For future reference, I should also mention that a few useful box and pose visualization functions may be found under [utils/bbox_utils.py](https://github.com/BigRedT/no_frills_hoi_det/blob/release_v1/utils/bbox_utils.py) such as:
- vis_sub_obj_bboxes
- vis_human_keypts
- vis_bbox (for a single bounding box)
- vis_bboxes (for more than one)

For example usage, you may refer to [https://github.com/BigRedT/no_frills_hoi_det/blob/release_v1/exp/hoi_classifier/vis/top_boxes_per_hoi.py](https://github.com/BigRedT/no_frills_hoi_det/blob/release_v1/exp/hoi_classifier/vis/top_boxes_per_hoi.py)

**Comment by MathiasHaudgaard** [comment]
I can confirm it looks correct now 👍 
![image](https://user-images.githubusercontent.com/10813266/57580914-19f40780-74b0-11e9-8432-bae317be883d.png)
