### ISSUE TITLE
Missing entries in hoi_candidates_train.hdf5

### ISSUE THREAD

**Issue by MathiasHaudgaard** [BigRedT/no_frills_hoi_det#5]
When I'm trying to extract features with f[global_id]['boxes_scores_rpn_ids_hoi_idx'] in many of the cases I'm getting the error:
KeyError: "Unable to open object (object 'HICO_train2015_00000022' doesn't exist)"
I ran a for loop on the training data and counted 7623 missing entries.
Can you explain why there are so many missing entries? :shipit: 

Cheers 👍

**Comment by BigRedT** [comment]
I split the original train set into train and val using an 80:20 split. Here's the composition after the split:
```python
{
    "test": 9658,
    "train": 30495,
    "train_val": 38118,
    "val": 7623
}
```

So your missing 7623 entries would be in the val set!

The script used to split the ids can be found here: [https://github.com/BigRedT/no_frills_hoi_det/blob/release_v1/data/hico/split_ids.py](https://github.com/BigRedT/no_frills_hoi_det/blob/release_v1/data/hico/split_ids.py)

It is run as part of the `process.sh` script that you execute in the following step:
[https://github.com/BigRedT/no_frills_hoi_det#process-hico-det-files](https://github.com/BigRedT/no_frills_hoi_det#process-hico-det-files)

**Comment by MathiasHaudgaard** [comment]
ah ofc, thanks! 👍
