### ISSUE TITLE
top_boxes_per_hoi.zip can not unzip

### ISSUE THREAD

**Issue by shadowclouds** [BigRedT/no_frills_hoi_det#6]
Hello, thanks for your sharing. I unzip top_boxes_per_hoi.zip but the zip you upload has broken. Could you reload the top_boxes_per_hoi.zip

**Comment by BigRedT** [comment]
Hi @shadowclouds,

I just tried downloading and unzipping the file and it works for me. I tried it on mac OS. 

Let me know if you are still facing the issue!

**Comment by shadowclouds** [comment]
Thanks for your replying. I tried on win10 but it doesn't work.maybe something wrong with my Internet.
But i generated the zip file by your code.
