### ISSUE TITLE
Configurations on faster-rcnn with res152

### ISSUE THREAD

**Issue by SherlockHolmes221** [BigRedT/no_frills_hoi_det#9]
What is your configurations when using res152 backbone on faster-rcnn?
(I do not see the res152.yml in the pytorch-faster-rcnn/experiments/cfgs)

**Comment by BigRedT** [comment]
Hi @SherlockHolmes221, the `tools/extract_boxes_scores_features.py` file doesn't need a yml file to execute. It imports config from a [config.py](https://github.com/BigRedT/pytorch-faster-rcnn/blob/master/lib/model/config.py) file in [L19](https://github.com/BigRedT/pytorch-faster-rcnn/blob/cdd46d4160f4762e9048a388c5a3d05f007e10be/tools/extract_boxes_scores_features.py#L19) and just updates `cfg.TEST.HAS_RPN = True` in [L122](https://github.com/BigRedT/pytorch-faster-rcnn/blob/cdd46d4160f4762e9048a388c5a3d05f007e10be/tools/extract_boxes_scores_features.py#L122)

Hope this helps!

**Comment by SherlockHolmes221** [comment]
thanks a lot!
